// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:

        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
         'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5z85tYiYBFG80kAcwH0o6iy-mRuw5xk',
    appId: '1:817910286585:web:a24a5d527ec4ba6b483a28',
    messagingSenderId: '817910286585',
    projectId: 'project-1-pracice',
    authDomain: 'project-1-pracice.firebaseapp.com',
    databaseURL: 'https://project-1-pracice-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-1-pracice.appspot.com',
    measurementId: 'G-K8HHHHV1DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAUQa5auU4jfnGlW5FvT3pCgbHRd7KYWo',
    appId: '1:817910286585:android:b1d67186f1ffbbe9483a28',
    messagingSenderId: '817910286585',
    projectId: 'project-1-pracice',
    databaseURL: 'https://project-1-pracice-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-1-pracice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE49_UDxUQw-pcvqAf1pBtNncdYpPwVTo',
    appId: '1:817910286585:ios:6ce60af721cd2975483a28',
    messagingSenderId: '817910286585',
    projectId: 'project-1-pracice',
    databaseURL: 'https://project-1-pracice-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-1-pracice.appspot.com',
    iosClientId: '817910286585-db1edh8sjsp352fulglljt574287udqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE49_UDxUQw-pcvqAf1pBtNncdYpPwVTo',
    appId: '1:817910286585:ios:6ce60af721cd2975483a28',
    messagingSenderId: '817910286585',
    projectId: 'project-1-pracice',
    databaseURL: 'https://project-1-pracice-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-1-pracice.appspot.com',
    iosClientId: '817910286585-db1edh8sjsp352fulglljt574287udqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
